### ISSUE TITLE
Doesn't work on Pi Zero W

### ISSUE THREAD

**Issue by KTibow** [RoButton/switchbotpy#14]
I'm running into this issue:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.7/site-packages/switchbotpy/switchbot.py", line 40, in scan
    devices = self.adapter.scan()
  File "/home/pi/.local/lib/python3.7/site-packages/pygatt/backends/gatttool/gatttool.py", line 353, in scan
    raise BLEError(message)
pygatt.exceptions.BLEError: No BLE adapter found
```
Do I need to enable Bluetooth, or does it only have classic Bluetooth and not BLE?

**Comment by KTibow** [comment]
Yeah, Pi Zero doesn't support that, switched to a spare Pi 3.

**Comment by jasonmhite** [comment]
For reference, the Zero W *does* have BTLE and it does work on the Zero W, though it's a bit flaky in my experience.
